# ==========================================
# My Discover Blog 配置文件
# ==========================================

# 网站基本信息
title: My Discover Blog
description: 记录生活中的物理发现、朴素智慧与未来灵感。
lang: zh-CN

# 部署地址（GitHub Pages 部署后修改）
baseurl: "/my-discover-blog"  # 如果是 username.github.io/blog 则填 "/blog"
url: "https://enen1e23.github.io"      # 如 https://username.github.io

# 主题与插件
theme: minima
plugins:
  - jekyll-feed

# ===== 导航栏配置（关键！）=====
# 只显示这些页面在导航栏
header_pages:
  - about.md

# 永久链接格式
permalink: /:categories/:title/

# 文章默认设置
defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
